FROM gcc:latest

WORKDIR /app

COPY . .

# Compile all cpp files from src/ and tests/ together
RUN g++ -std=c++17 -Wall -Wextra -I./src -I./tests \
    $(find ./src -name '*.cpp') \
    $(find ./tests -name '*.cpp') \
    -o tests.out

CMD ["./tests.out"]