services:
   server:
     build:
       context: .
       dockerfile: Dockerfile.server
     volumes:
       - ./data:/usr/src/project/build/data
     container_name: server_container
     working_dir: /usr/src/project/build
 
   client:
     build:
       context: .
       dockerfile: Dockerfile.client
     tty: true
     stdin_open: true
     init: true
     container_name: client_container
     working_dir: /usr/src/client
 
   tests:
     build:
       context: .
       dockerfile: Dockerfile.test
     volumes:
       - ./data:/usr/src/project/build/data
     container_name: app_tests
     working_dir: /usr/src/project/build
     command: ./runTests