FROM gcc:latest

RUN apt-get update && apt-get install -y cmake

COPY . /usr/src/tests
WORKDIR /usr/src/tests

RUN mkdir build
WORKDIR /usr/src/tests/build

RUN cmake .. && make

# Run tests
CMD ["./runTests"]
