FROM gcc:latest

WORKDIR /app

# התקנת CMake ו-GTest
RUN apt-get update && \
    apt-get install -y cmake git && \
    git clone https://github.com/google/googletest.git && \
    cd googletest && \
    cmake . && \
    make && \
    cp -r googletest/include /usr/local && \
    cp -r googlemock/gtest/libgtest*.a /usr/local/lib

# מעתיקים את קבצי הטסטים
COPY tests/test.cpp .

# קימפול של הטסטים + קישור עם GTest
RUN g++ -std=c++17 -Wall -Wextra -I/usr/local/include -I./tests test.cpp -L/usr/local/lib -lgtest -lgtest_main -pthread -o test.out

# מריצים את קובץ הטסטים
CMD ["./test.out"]
